### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ThatOneCalculator** [bunsvr/cluster#1]
Especially if this is going to be a reimplementation of `node:cluster`, I'd love to see some basic documentation on how it should be used, where it's currently at, and if there's any future plans

**Comment by aquapi** [comment]
@ThatOneCalculator https://stricjs.netlify.app/#/basic/utils/clustering

**Comment by aquapi** [comment]
The API is kinda similar to `node:cluster`

**Comment by ThatOneCalculator** [comment]
Nice! I'd love to somehow see this in mainline Bun soon....
